apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-config
  namespace: openshift-gitops
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/lcolagio/gitops-for-organizations-aws.git
              revision: main
              files:
                - path: "clusters/**/conf.yaml"
          - list:
              elements:
               #  - template: admin
               - template: identity-provider
               - template: groups
               - template: hello-world                     
               - template: web-terminal                
  template:
    metadata:
      name: "config-{{cluster.environment}}-{{cluster.name}}-{{template}}"
      labels:
        environment: "{{cluster.environment}}" 
        cluster: "{{cluster.fqdn}}"
        region: "{{cluster.region}}"
        cloud: "{{cluster.cloud}}"
    spec:
      # syncPolicy:
      #   syncOptions:
      #   - RespectIgnoreDifferences=true    
      ignoreDifferences:
      - kind: "Secret"
        group: ""
        # managedFieldsManagers:
        # - Go-http-client
      # ignoreDifferences:
      # - kind: "MachinePool"
      #   group: "hive.openshift.io"
      #   jsonPointers:
      #   - /spec/skipMachinePools
      # - kind: "ClusterDeployment"
      #   group: "hive.openshift.io"
      #   jsonPointers:
      #   - /spec/installed   
      project: default
      source:
        repoURL: https://github.com/lcolagio/gitops-for-organizations-aws.git
        targetRevision: main
        path: base/config/{{template}}
        helm:
          valueFiles:
            - /conf/{{cluster.environment}}/conf.yaml
            - /clusters/{{cluster.environment}}/{{cluster.fqdn}}/conf.yaml
      destination:
        server: "{{cluster.address}}"
      syncPolicy: {}
