apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-provisioning
  namespace: openshift-gitops
spec:
  generators:
    - git:
        repoURL: https://github.com/lcolagio/gitops-for-organizations-aws.git
        revision: main
        files:
          - path: "clusters/**/provision.yaml"
  template:
    metadata:
      name: "provision-{{cluster.environment}}-{{cluster.name}}"
      labels:
        environment: "{{cluster.environment}}"
        cluster: "{{cluster.fqdn}}"
        region: "{{cluster.region}}"
        cloud: "{{cluster.cloud}}"
    spec:
      syncPolicy:
        syncOptions:
        - RespectIgnoreDifferences=true    
      ignoreDifferences:
      - kind: "MachinePool"
        group: "hive.openshift.io"
        jsonPointers:
        - /spec/skipMachinePools
      - kind: "ClusterDeployment"
        group: "hive.openshift.io"
        jsonPointers:
        - /spec/installed                 
      project: default
      source:
        repoURL: https://github.com/lcolagio/gitops-for-organizations-aws.git
        targetRevision: main
        path: base/provision/openshift-provisioning
        helm:
          valueFiles:
            - /conf/{{cluster.environment}}/provision.yaml
            - /clusters/{{cluster.environment}}/{{cluster.fqdn}}/provision.yaml
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: 
      syncPolicy:
        syncOptions:
          - preserveResourcesOnDeletion=true
