apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: all-openshift-clusters
  namespace: openshift-gitops
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
        - key: environment
          operator: "In"
          values:
          - bas
          - dev
          - qua
          - pro

# apiVersion: cluster.open-cluster-management.io/v1beta1
# kind: Placement
# metadata:
#   name: all-openshift-clusters
#   namespace: openshift-gitops
# spec:
#   predicates:
#   - requiredClusterSelector:
#       labelSelector:
#         matchExpressions:
#         - key: vendor
#           operator: "In"
#           values:
#           - OpenShift