apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: {{ .Values.cluster.name }}
  labels:
    name: {{ .Values.cluster.name }}
    cloud: Amazon
    region: us-west-1
    vendor: OpenShift
    environment: {{ .Values.cluster.environment }}
    cluster.open-cluster-management.io/clusterset: all-openshift-clusters    
spec:
  hubAcceptsClient: true
