kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  annotations:
    helm.sh/hook-weight: "355"
  name: {{ .Values.cluster.name }}-aws-creds
  namespace: {{ .Values.cluster.name }}
  creationTimestamp: null
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  template:
    metadata:
      name: {{ .Values.cluster.name }}-aws-creds
      namespace: {{ .Values.cluster.name }}
      creationTimestamp: null
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
    type: Opaque
  encryptedData:
    aws_access_key_id: AgCb9DRwqPzI6ASDjZn37L/Co96gu9IETewB7cxXEhbnnBAwEndcwetSfi5SJbYbGFN9ZRKAT4KriB0H6kUgZYORf7lkaOEbuspuk3YDPsYpaQsvF3HzP7W4gIxCLSCv9QmEBVSM/BpisC7HO6VNztmIySE8XCstazBfHgvicY5gUaSzVJIl/LFPcRUiDf6m1hYgdYnzW9lKKbcD9TbZNnCAQi58CEeEu4Je2cxurWdYH1P96a/7vc5I1XWwiaSqBI7VEm48VDs9pUEaZAVKcmk7eVjW3TtU6fELlX6O74Thgdt4Tfd+HA3nydt8jXHVum6KncBsNtmViued0Z1+/JBblX4cm0f5rI3O/hmb3TTPL+hZbaEbScl27+80BkLhOwltkAjczU8TBfdxWEYdUkFMJ4vXuW61nuXCP20R4Hxm62m2JwvyrxusFH+1n6r3+5C7cxBqAhUHZJ91vARProeMA1qjMOLznoJSBcHdtANJUUxSP6rO5hBdw+JXRQnVhrOebLYKf/Ajd3NKn/0RgVsYpdQcebV/FRdWROkN2wI19eAlY2tCTgs5dH80/VSCJYGNbOSIpZZWKp0rvNImi9MnVqDjsPNoE0+umGZZdF3+JqS3de+XJRaXxhWu6hG02lDRFJbQfyCc/o34n+drW+KeGgH6QOUqYudUpDlGnUSo+kgHi3Z4B4364ULtHG2i+d5aHs5tdjqAvJl4jAUpfRNDD43XhQ==
    aws_secret_access_key: AgC2/VUa3zXVNcjXBzKYfK60ilDux9lk9kL+moXIHuqvht8D6o5sHqwFRQWVHRrPMrDMulc6fshCanqr1hpDw0ymUTClhayxdertf0O6sC68grTcxFTmZtxcR2/4OgQ8e4/0YPr7HiTMCtoeBKofzp2ZRv+c3FZ/rl+AiwKgAXzpcKyiBVS3hDHy5Ar/GhmKtJTvbbp6LP+2grUpYJgWqxReOGeJCxFV7e4Z5MNXqGnNEkCMdDEE9GLmOggEX2/cWQ2/yU/IUo7rfqDbaICJBk0D34WnUfmQqaiaFNmqOQ0mYZgrWP3w37AEkFWy3FaqlHMnvBHeyFk8IqxTU4OQr1QYffo9LPccjGCoM9Dg6tts/e2NFn3Qtrx4/f6u6vtJCb2ravFmVKN3+9CkOE8kTyokEn35RAz7xZ5jFoV+2bKxxNHsHT4vC2jrECp+VHczwwU9dLGuZGfVOqwRTXUUtFYmqT1Q8JiVXIAZGk29LDwCk6cr6HhgpfDaYni1qxjXwe0S4MsNxVa1lCct1xGqea1OrSmZ+np3WkNhIxkJdgbuZ7Ysaa7Q0+sVXqi10aS7arQmQsRgtSxea6KkV9nP4aD8w8ozKh3Fnu/xJji1IqfkUAdEQGuhag59AhzuOEXSx8RXsgc4KJd93Y1mJLmvaKofSXHA1gPu8sjFiAcEZe6h1KUKY52OsTuCDsbHLUq7ao3xzxw4QE5XegQkv+3hRmXTbgWpaCArxPFvH2XtEw+8PAv4//m3go0M

---

# apiVersion: v1
# kind: Secret
# type: Opaque
# metadata:
#   name: xxx-aws-creds
#   namespace: xxx
# stringData:
#   aws_access_key_id: xxx
#   aws_secret_access_key: xxx


