kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  annotations:
    helm.sh/hook-weight: "355"
  name: {{ .Values.cluster.name }}-aws-creds
  namespace: {{ .Values.cluster.name }}
  creationTimestamp: null
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  template:
    metadata:
      name: {{ .Values.cluster.name }}-aws-creds
      namespace: {{ .Values.cluster.name }}
      creationTimestamp: null
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
    type: Opaque
  encryptedData:
    aws_access_key_id: AgAS2umTkuZ4DJ1rXZhpTy4JI3w8jX4r0e88MjVrrWGblyKHSLm9HPORzYxof2dU1EIqz3quh7sXaISDsZ5VJurkzh/GQwh5yB2eOxCa6R5BVtDhvr/GbkWsiw/EY758KA2BWhKal9Es9pQlM2XbBYfuTXu2dZxW6rjAHrw5uE1djpxt6kk9KQDVMEbPr2u94J+NaUCNTqDzb/66hzWmhzykPVHK3jHmtjYuqVybkMDyJOHmfSxBtuqvSodgY88M8aN+32blmvlWHlFavqJu51Cf0yig2nY4FRsP1x8beZ5vYfhUvP/lOwhEDyD3pZNkCgYXuDgq3AFfsXmNpaoAXUKMJs8MZ2Q4NucqFgaNIMS7H7X7NuMuM3sqwGY/Djobjf9LNqoMSY9lcQwqhwjh/XCTkktma+GAkk6eyY+WrlT+gkpXzmnh/7aXuQffeDnuf3Y6ng53HW12wgQA5+DkX7beseBM10M/94PlKFw0U0WlTjW5U4R+eUD5BJ2QJDw0irvvUu468eUSGDRXc6BcZki/LA1T2mto0nBHDLyIyaHjrFuYkdsHs2DFIRMXh1LWA6m5grieGsjf/D26etJHTBFWWdQOrgs+MTgzNObT7j+deMZkhdhN/2SmbXSykMnG5S12glzQAhx5SM+y+LdEkKW6Lps7ULNWo70gflm/fsIl10BtnVH0L0DveOhGPILeJWy3s1Q5Qz+oTzs8zHOORiraTjRu/w==
    aws_secret_access_key: AgBP58o8F+aDhebVF82INLou7ozx6vO3XtvLy9I0LeTQyMZSMUbCaTTWjQOIzgwSY8ETO6T6XNfHYVIduHbyh6t3OvX//JkIpPi7FlmMe/CXXf3MEXobsOJWhXpJ2jhz5y+AUNLG4Ud9PfhUdf+/yd7bOaW/sniniHut8N9GDBCD/XGTouPhFNGS11KqBSUmX1gFoV7Rw1YeDozbuTaW7TFHxBCMwDhA3BOpj96E9T0FY7tgFS33bFACdLugV95hG5Buajofjcy6t4Pk5vnV+gmE3RPmtrnt0MSPJw4mfLveVYYzRRLmU79pf52iR57GQFD8ielLox1g3RXLgqAgG8BKF8pXFA6XAsTwD9FZHB60Qdk+q4BZGCGRKPq3xofUT+eUH7Ap2FqQRe92uzrK0FIIIGHaSYjtRCWeXpRXQK4iTMKvtzhlLt4owTMQ6QkAlU8EeQm1WwPvKv5xnRnIjll5H9WN/h5fUlxlrHHsYCAICsxJ42DeFPD0qYQ+VQH2YfpFylpLwnicGrZqp43PdT5RjVl4IhA5bmWd3d5KvxfdK0y9zVaUaRak+kNzURIQYeMTLShBQWboGbNhEADIDy/LjxgGBxhzqS7Jw1xadKgsbXQtLZlNRF+GNS78zk+8dEu44h+Bge29kGCuNRq4n9KqxP6ebVs1KLFuggRwotR0VkjaEK6rf1a8myBsstFwXxN+mYohxKnKGzQqpBNcGJVQ43vbQtkntGdg9dTuSZp8Z6JPSmBYJbcz
---

# apiVersion: v1
# kind: Secret
# type: Opaque
# metadata:
#   name: xxx-aws-creds
#   namespace: xxx
# stringData:
#   aws_access_key_id: xxx
#   aws_secret_access_key: xxx


