kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  annotations:
    helm.sh/hook-weight: "355"
  name: {{ .Values.cluster.name }}-aws-creds
  namespace: {{ .Values.cluster.name }}
  creationTimestamp: null
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  template:
    metadata:
      name: {{ .Values.cluster.name }}-aws-creds
      namespace: {{ .Values.cluster.name }}
      creationTimestamp: null
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
    type: Opaque
  encryptedData:
    aws_access_key_id: AgCBgk+LFng2nQ/4eqLwJTSkEzC/EGpbnQSZ0PMkMJsCknq57CoX0C6/dmG5yjDOx5Pjjcr12VI/FfI4h+Qc2gwP1kXUqfbsLYF+Bl2sJwNdreqyge7h7BVqq1KTTiKCPT9vuGyoybCS6dFiF6tPBS7vU0YloCr4wdrEOxvuMT8nLWzOxwY8hrzSQuo7DPYpHUruGP+2lOeyqVfKlQbzRnAno/c/hc9bapI1jFrt2TDZAZpd2HewcYdWY5MYgGGDeNdRyOe5cQiEROrfyGrxa7ekwLnrDKvxMm+43iAPED94MUDGARjF6sm+wjH4BE2jySWS3uwdj/HGgspeH0KKmTs3JhFvftz7l8elBTZlVmvrFaPrc/zGBJEG/qmzw8FhZhZgmKfQbnLbeoykKu0+7h16k8qq/OeczmpqRzzg95mnh6FJM9pzj9XDRcznxcZQh2OB/sX8pESVpJq5tce0xuo9qxV8yJ2Zx/WUX9aGoCrlMt7I3LUbLqID4IpmQF0GH4I34Efk/EfpO8gWVY43MQ7H+WqIdyGLRp0Y3DojU9D7F8HdN2myRDE1Si+S5tAgPHGs5TDDMZfvHWJc0k/FbHJUJmkCP4BeHoLndyQHzi1aSv2WaL30Z9uY2t10W8EMDK5mcb4onb2kMvLm4VmtNQUPPCpmjPFTGk5VaKxfzKQjuMlYi1GcSNnKb13cEV5TOOjhGZIdokpMO0TCvi+cG2y6U+FmpA==
    aws_secret_access_key: AgAh9/lW4JKAn2uXA0hfbr5bT8aosrwJe/2ju9wUO62oaiyR4uDl3Hyy6gd1a5YcM7YdZu3c4i1PpscfghUbZ7qAwkepWIZnea6ciGO+azGRWlRbGL9AbnggzX9LfIAjIYzkf0o9F53xq2u/Tr+cIAV2sqRsLRrj4j5x2ewLQuaYpWS9nUodD2fvacV+moyeHO9FfWX2TZIoDpLiLxGc4M6pLryN59yfaXgs+rzHnBL9TTYAJw/t7ymB3bmpB80R7X+K0k9gROsS/TKEpJ30JtwxpMwBMnPBKBTQA+yoIghimQZLCf5YIDeDrYedpIqwB802TAPkPbn2SmbMJvPyjoHOBGRSysXwutGZO0pEM3iKkFY7KXO97Z9zg+o1J/GG/C1cy82THsyOzk/IDul6OFkz5d2KE0Di7FO86Yc4bS94xVXCL2HM/Hzd+W7lBWJUrqN0Prcf2EG3X8wDkUFytaxEgYvOGVYQ3kX79UVHuEu8WhRO6CDO23ZWxSHS1loNknMIEW5eDy/Ek1Ih14gqjWZ76Z6AS65GG4/hpYMMCIBFiMri1PZ2UYXdC5Iq1tDl9PsYH4npw0JEa5FqJmNF52g7ZfPbGdXb3hpQGMeIUtg/EY8FSQPo9CGpX3kZVXTgaCi9Mm9QiGGCuoDdnflnUyVGwrWKhIOVPp20yzpRRf3ulNS4vgq/bM9y3Qa9zblBH1vOtlx4xb1QkKtws/lFZfKPCnXIoAXJ0fEIIPA/HWPnWD3qwvXOElyP