kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  annotations:
    helm.sh/hook-weight: "355"
  name: {{ .Values.cluster.name }}-aws-creds
  namespace: {{ .Values.cluster.name }}
  creationTimestamp: null
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  template:
    metadata:
      name: {{ .Values.cluster.name }}-aws-creds
      namespace: {{ .Values.cluster.name }}
      creationTimestamp: null
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
    type: Opaque
  encryptedData:
    aws_access_key_id: AgCuCr4TAygQrDOlQ/1qWQxGeFVxUf3Zof1zOq3KigZpgIYJAL1cY6sfO0FAEHmEEbTkWsOv+WxV+gC/h8AJCfJZCCy93C4vV44ETflPDV22QFiZlI2KAfQd8345xIyRw23wlf3Q3cpvgjAtd2rLQzFTchMkm86DKLPFQ4NA2lVHO55lDxWx44bn+5s+vSNYUCsX+Hlj6D+7JV2W5zj1oXnYeJC6t3nDIUkU6GfNMEi6p/bQKGsQROtBTFw8O9Te/M+dQ0dnWsdj6pYd6SDv6ZXze7ujDch7LRjNkTHV2Tl28DD7pqxabV8GmxGFxm9no7kZlmBtYkrK9Q5tKU6PqZkN7YaaD93u6V8AmAX2Z8zuTXtk23hNeaWvQ4C2QEUUFVcUcfKUjCIeJ8yxC+/uKSSpZPxLaoh+rh9B+uMI4aBNOMLE3Rccpu5zzVNpywp2UsB+Y+t9i2xVWRAEShaqRTBVeRjTe+tlM/E5/5WwgfIuklgDCMwApGhHxYanMJMo9Sd0Mj6ZmGUSOC0BFMe3Qku0qA13H1b+RROe7i1GtKuX+vVVWsHvMJv3FjA+0h24z6W+RyomSHrkggPbCU/ZtFSziJxJOHeuidJyvtl737qNfcbm0V1RUoVkxqvglXGfn/+bem3vmJ1wuP9zVhXE7ZxP5qJD5lwZXxxRkY1N7kiPtLasLpJT1RvmNKcb+Cv8RDC0+Csnym2KZcyNzIJzYKYM6STkIQ==
    aws_secret_access_key: AgAzssgQ7si7HDYVL4zT9/taIhnDkOV2Al+bJlaOREVwHzFvRdednSD36ip4sV2SseloUonS5kYsXR8osOEtQp0fYd3q49akKJKOhvCbPwjgeL23TWdrhRYCjhzkfr/JrwyWK++71pspYDZ25toNFkkVY0vcgHw7IGRF/wgrvFxvu5ZOgcVaNRW9Ql2WTiXNWQjNBHLe0AaDvGNI0pdSVklawoein1DhsCJvvJlv2itL+O64YfBHSX9IyPqWQsI25X0ElpogoqAnXlBVPR2e1W2UfBF7k6SlSlHbFoX7k7DSGhTeU6TKG+bNU/1S1sWEeYVqW57nt9PEG+xQvgS3K9B2t/Yrp1bbkamm8BdVvRHpCGpF6TfFRWJ8dtZkZg+KXmTi2xe3lviqB3QkCyOn3Fnb6S7I/Sktw/YisU+V7Ho7zffHLu9tnDu9zRrQO2qfY8J8fKLfWXdQG/iuShBslTdCaTVTa0gDi4KCHGS0OkHji4keFwe0G6OrhLNftZLxB3OqwSmQsDv7NMtFWdtVie4eBdmEol4AENUTIA+GUTti26ykHSgH7u+bJWCb7Of2EJqNTxxQFPFyQWcjj9rQhAhmD9uCQd2bKM3YGdvXdT+dp//lp7yC2v4gVN4xxfMpzgCeJwnIVBR2OJ3tQvgsXH9Z3dRSRi5ncwAvfqGgLXoyhKFshvlN23U2Q/c1cEQfQNpleOUPkUKY+K/nxjqcegRRBTTkuhygdVp1n9Xc1TTAUQH/nKi3b18h


---

# apiVersion: v1
# kind: Secret
# type: Opaque
# metadata:
#   name: xxx-aws-creds
#   namespace: xxx
# stringData:
#   aws_access_key_id: xxx
#   aws_secret_access_key: xxx


