kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name:   namespace: {{ .Values.cluster.name }}-aws-creds
  namespace:   namespace: {{ .Values.cluster.name }}
  creationTimestamp: null
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  template:
    metadata:
      name:   namespace: {{ .Values.cluster.name }}-aws-creds
      namespace:   namespace: {{ .Values.cluster.name }}
      creationTimestamp: null
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
    type: Opaque
  encryptedData:
    aws_access_key_id: AgB6O5kWlTLeMCqpUUGnVb23ppm9Fc5f1vfOeucNxoSXTu4wQEKPubEOPDh11396lt0KeS7OU4CjWrltODsS5WobUiR3J8qXKOxvsJrDwtlAlWDyttQ4j/yp3bAJvCTlTPSLRjUxWjKwniQmPRtQ8rw+gKNPqFVc4lLG8gCAHityFy4ja+E2vQEQMdA8c4anOVNRYHIavUVH6BZwbcynjgLmsJ0ceRgh1we8mkUbGRV9jHfI4JozGbIOlZ/U1Q6/0K87toWp5PO97Ah7ftH2xS0MUS535l3g29fPmBcGlLj7NBHXRBLDirSNO0qBrM3Qbj+7P0SO8TwhQPCkYvUh3R/mW9FXhYKE8VlrRlC09W49wWN8IgOPZg/V+xyWPCk6Mmx/QrAXUlV18HmRZbzhGlPIzH2NtT4fBJKyjd9aR2omCIxTci9u1DOOwNx3KdAf/l/EX0Uful9um/KWQHMlePchW7qa4149Y6Skcvw5cYczVt4fo5RXKZwO8TOe/mY930E8xYZC6/hTkj4RSV1veBVi7ee5U6vLybbZkrX0cTvOtl7JE6sFwyKmOCCktNIO9FC+dy2DPnhcQlxvk00SJhDb1MgRycoj44HmpWITKLDMkvh3bXS4qReTojBzWq8chbcaY7pZMV7t7k6GqTIJmL/EDV2x1gLvPim0Jt5bmXwoPCy40BEeRc0d7WOplnO9w4qEomCBrDX3ASflg9eyp7YBSsISPA==
    aws_secret_access_key: AgBaOwsHC2dW7UDc35KrORiEyYVNvRyHQDHuIBGoo1kQvt+cfhIhxrZhR0DA9GNEWsu0u3CRJpouJ/4RtER1kkm8sudelx3y/NXWqySYvAmV7oXxK11XrRQToHhv9wcUHAxkzLCW1VPoF62VH3o7hawERNNoGoylt/+joPuuPiqxEGbbN+cpopZeKbnqR5gdBAVZpSyQlJagKyOC4QQSgVYgl26VhF0R6ss65a5JW5A0m6K2XNzyIXvWfHeLpR2fRTweg+gYYKw9d9Ch7BpmioNpC3cmOdtiCM4AVE+HKVDahCICazwYP41VwY/4DeToURQrHsYxIFZN+ukhWpUrHvvGFrvNEUK2pweVDZSq5OwZwXg80254wlsJpndYhKh3Tb17mXMYDIqLh/CnpBIZNTP9Q00qHAlIc7ZvDo0yLUW0U2bVrjNQFvliA1z36+l/PEkAtpICIIMJhDRWmwxty5x1MyLydR3zKMr4xhpUHqgJbB7HTsXDa8gTaOzVUK3bOkhk6XzmTQKOME93Ru26A5MRIkHPsq+MYp6Kd8xkW0mBPCeQcpMso9u4BvrxcQ6u1X06GkBoTbFXAK/aqZb1FlZ92MAXxeMK1A2mpBE0/Vjmr/66SfiNeva474mpjMwVDYdcIvGiC0tj7HWN8WIyNKYA2lcaRkVctffjWo8JuyObDS7x3rl2ZZ2plsnOhA9aYDaIap1hINFh3ANOtDIiYJkMkVxb63j0paJCXwVjeEXYV9T6q1Ua+Xa5