kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  annotations:
    helm.sh/hook-weight: "355"
  name: {{ .Values.cluster.name }}-aws-creds
  namespace: {{ .Values.cluster.name }}
  creationTimestamp: null
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  template:
    metadata:
      name: {{ .Values.cluster.name }}-aws-creds
      namespace: {{ .Values.cluster.name }}
      creationTimestamp: null
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
    type: Opaque
  encryptedData:
    aws_access_key_id: AgCN2kmcDuw8nQy9Ty2ugbvOlvL6GF+nKkLcAoo9r9R5JDG2ooDOVw68r7ojHnDMv5t0I8769A/pyDktJis4vbrA20BpS0E8eaANjXgZYN0XOLJ3Lyg8ZRBxGRiv7bpV7a2KSzOt7jUbM13V9UrnKYSH2mtOh1/EVXaff60viFQoyBVFHTnsMkxhX4zuCu5uNPi76PyoABdZxSRkt2ASO2F/ejvk9DbhbTrWPhaAuEbN0wbdqBtU6XBUb+GkQ5EFe6Qjpe0/XUPv8cq1VASVbRv1RBBDLw8vqPiKhg4nRHJj07Fto5ve2k6hApA5ET673CqEmCq/M7uJxHMOdlypn5UQ3XjP+mcD3UX/fAJ0CF6OJJULiwQLCh17u4lB/VOoExU3vWUEhuQMQzAjYWGiY+YLYREWC8h7Xb9D2VAo7KCDKInml0n+nTN/OAzA/xNCzuIvNr+LcH53SnsxoNxZw8y3kGXmo60lTqQUI/q2KNi9Ui9REYSRju2SLf7TzhU7e4DpOnZp7gBGo1fmaDTmPylRJNndvMNiKkI1dAvUIY9vkQuLqjFtGmnfIxI9M741w+XddnvNQkG0y/El9jfd3vxE+n0bZMY4Hu0o2ocpwk3SX73K0Y4w9rkeyKxDXRtyafH04Wxz4Ua8BTDHastQbHSKNY9bnViYInb3kpV8i/3uTj4YvXKIQhOYmlJDb/dzcOK1Os1FKD9KKwTYeK3Xx07wclf5nQ==
    aws_secret_access_key: AgAw3cpfUOxgbKg8YOvmRuplBm70NvOT/PSo2rVXkqwmsJKU5mGbrFfsrNSqMprL28/22cS6Eky9TgLjvnLz/mBaTCp+QJnl9SjdLiz3A2m3RLOKqojeEbHKl/VvJ8T3F7P4nbatOp7V2wV8OP1AsoZJdWQ3Wb8PYBYWppT6Hdeff34u7pd0pejvMzWf0VpHFMfceP7McolsxbBEkCWyqkGX1LtUZVYcN+NMgo0xX06sw4gACHLtZNtfw3GhUFll2dawRlt9jrH8YIdhgEQZIoHXmUZqUAlSuZ5rA9b1EuVh2UX4OW5z97SNMJ1QH6eybrvXUNbtfDa8ueIq23XqhnUcMTXxW/ZfLSrNj0R4j9Ds9lVXjB/BAvKA7R4g4BdNdiIZGMJ+xHcMRJcrReHAmBo7v6GizNAZpNtDEByXnL6ZrRgL/dBSyJGeO20+fbAzzwVGaZXwhAJwc70Pj3C0O4jau3bczDeEFQyhZaBNgEuhgSsp9QSQLi1SWWtStiMbZ12beRNDBruQXJK+I6dYS9EPYLE9Sh2lS8NPjCPToDJQfqQbe/fpK6u+nDk9efiqbL23eJqL1YTVzatM2bLVda8LwR7hLFQNXT29L7HsH0M2wfrD6Z40k0Lo5Bi4eD1U1P2LGyKI/C62FY1Yz3H+NZjgb0rP5vahGceYr9npTPN7X/Rre9nBUJKU0faX29UmUHd2sLuQkrNUQ6p0qLyF8mvxw1K+CEQrabxzmMsW500gy3M70ezQ44wx
---

# apiVersion: v1
# kind: Secret
# type: Opaque
# metadata:
#   name: xxx-aws-creds
#   namespace: xxx
# stringData:
#   aws_access_key_id: xxx
#   aws_secret_access_key: xxx


