kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name:   namespace: {{ .Values.cluster.name }}-aws-creds
  namespace:   namespace: {{ .Values.cluster.name }}
  creationTimestamp: null
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  template:
    metadata:
      name:   namespace: {{ .Values.cluster.name }}-aws-creds
      namespace:   namespace: {{ .Values.cluster.name }}
      creationTimestamp: null
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
    type: Opaque
  encryptedData:
    aws_access_key_id: AgBlHDPRnVw3DN1asrg7x1BXhDF+jFCPOcRIhpI4yHi59QEdNZMiB2P/SMqE38Xp+XdRrr0NEVG0G2NsrkhOOzNUFSn2UahNGJO+aV+ofROnRxDbCjf2D/E3f/jng5FWi+YwP78VH4zRum8nQ13rDBjHzprGleIsYQIGvJsRDc3Wsw9oRnLFj8/xFSNl0GnZdii6UBNa5w0UdeFhy68dhOwhs0IqYAtQTxCbi/v+nRmxpjefClbB9MAkLAYvTaOPXFsTjVgnV1umVWaqMehVdeTQIHjmW8H/iZVZ98NUG19iSEjclP6Mlcscq3a5/F2t0qLg396rJe1/YZNk0uOlxC69wVbYqxni1paoGin9dTm2kIxzqseDiY2nKBSoQJGhLKc0XHZJNvSZKCbsn2IU36KVtsMU/jVs4bhKqP2nY7WhqpcFF2zk4dpvB4iyNXajITc6aGnh6GFvMvIOoYdiHMb8b+/JlbzL9d+qKHeSKNpEi+U/kdNVLUg9CdKngQV/UqR12PYpoO/c0JlRvDuwKG72NcLSdqFf+MqrfYDO6FredzWsRuSM9V1Ppj9ZyNzF+PY8S6hPCMPzZ2UyHG6BLo/G4M/szn2gVTsWag7ge73ZMMgzJiUgXt2VjJu15mFAY831MSelrKN+Rk5eIdMYnSgCCcwt1OXbrIj1xHYAVZTsocS+kBzjLVCQitySiUYrc6h6aQMZLIK6gGzV/n7Hio4k42adBQ==
    aws_secret_access_key: AgCq+zXzrfQqj8230lYThaIPE1b+bPXfgdULRfpv7RMgYBnaqV2kdKNrdqFfHtAs02PZakYh2g+cm27CWQvl8lramAiddVZ1jkK+sPTfAZ+1dOCD71QuZupQrfKPGT1sNB2VjEc3+gRbSbO/Z2Ja7uJEavdqGL9b+X1JPTwdPvnGXTed51ZlUD+J6UczNrQGxDCHVVwtMoe2ZQmmSekh1Fjpshwyuu57Bdocins3pXTGnDq2E//1SX+vqLM3CDWwjp61OXEbwGvBrolUcJa0pNQv16KtDP8sxlFYvD1aH2keWdqhZPnrveiLb0FKY/qJRlWRMzz1P/+ErVmrdST8XJKl5UD6IgCCQevSQst4HoG5I5bslC9JINDnkB7OpsdaBWPkE3Klsq/E6k+0rKLG1snfhAl8JmbxvQH43xCq+pstJFnlPFisfvRlnSWzireqhZaejHOvL9D6O3stN7ftPONKRtZXRTK5Ytt5zEZa4lH8mLfpMWGNOiu0FapCUQaTDQSvRr8FZ95Df8YqPlKKLFqYfTeemgr1Ycz6rolsNf45oi4deA3DYvJIzgQnu+P99kmAVG7rzgDX0CYiWwpX23RnOzWHPJbSxAbiKPEbfVl8lkFT9qH2vidwmYoTJ5RZx0aYPdNRnYJbgKFMuBmDHCJPtBoI7XBWK0tJSBE4bur8QqaS/t/+E48/lTN8zRJSa3FG6ndDvjbO3EbyAj3klrQswIna4IkdmKp4DQpkRf+Kx/Mmq4ICamQz