# apiVersion: v1
# kind: Secret
# metadata:
#   annotations:
#     helm.sh/hook-weight: "355"
#   name: {{ .Values.cluster.name }}-ssh-private-key
#   namespace: {{ .Values.cluster.name }}
# stringData:
#   ssh-privatekey: |-
#     -----BEGIN OPENSSH PRIVATE KEY-----
#     xxx
#     -----END OPENSSH PRIVATE KEY-----
# type: Opaque

kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: {{ .Values.cluster.name }}-ssh-private-key
  namespace: {{ .Values.cluster.name }}
  creationTimestamp: null
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  template:
    metadata:
      name: xxx-ssh-private-key
      namespace: xxx
      creationTimestamp: null
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
    type: Opaque
  encryptedData:
    ssh-privatekey: AgDArUPfxgnq4/Y/nrfoSE6g3IQKp0TgoCwisB334ZfnwlXXAJdxvHBbPf5A3DmyTDcLCWCMIY0yIsn51XWI3TqNrVxB4ykykgmLwKLkU6asF9G/R25bUhSKyfBaE1LF2uXobLPDWx1tzTc88OBF59hmJIn9h1x1IR7AHfz77AvlsNTMZirXEKePDR8jd3Z1YujqyoOyJxOUtYaKZNXtJI2M6dP/pVF9zK9IYzqRSpGYv9K77pv7VwxVxdch7Y1psuyxkLH7Iwp24NQtrtUrPUL4fDmzugZ4xLfocvFsQkSaZXIVxyyt8IATyGDCs0RPZIkhU9CVb2IL7isv9t9EPOVOduc9JI5EANggjsn3ImkzkcK+AlvD9Gv+xqBPNX2Pwn25usUtWsrYg8dYHuVPb/imKkDiRjBy5ozzkS33xss8/6bxjOeUXDileivA3lv1H6UGPDp8F+PULxGOxj1xw6d1zBdtWAY/uBO3H4wrTSKE5CC21uZf3kn9FZ2iLBHbX72CGJm2KJH7OdXInC6jkW4rEpR4hRZR2j9y8O/6+Bj3F/kkrfGRURppA+n4yKQZP3wHccs+LfLnEbPsjrAikFlXHne98JzybzQiH9oLI5qC92JabeLnn8qjW2lTcEJQfV//X9UD6zaVIO+8mNZdcqWDyx3qRWva9MED7lKH2YxkX3Ky/11gLlFOKDV3zAX2OPNmhcm3x+49w2lSHdovujACd3j1O5k1zIbFtP8QY4vBXU2iYDnW+XzmA/gvloSD9NfXX7suhU9W2ESSA5Kt5e2FLoukWTWKb8XufE1xB37W7CxgR4CcTh4B8rTOs9q0ufyi2v082rWAJzXZ+MwDdpoU8MxfiHsBQY1IrYG0o575DJ1LTsf+HqWgzCO1aXL+unIHrvfbrAjICUYAgXx4sA+LwBHJyMFeiIFRdWVGazyZS0/xER/uUcD+lLk8SNu5bHTRO3LPkA9aARFW5uRNKJ0kNS+sDRm9QPcihdtrOijYWLP7W+24TSCbXIq1eFfOa2yeMRcqUYNeMAgECz29d8GEEKaQtv4FrGFKhJo1WAHxNidYsevDV15b5fzBqQlHaQTwpg9cepk1lCuCSNSS8BSKqMn9gGMs8M20EnUsuCNJGj+wVXG/rRaZJi0nLtvMoiuoqlaJygukkD2NXEKpwVLl30Fw4Bpc6pf3OpXFbELW/57eoT7Bi+dA/JZZT4nPeTpH5+BtwwLEjvsmhjLdJ32WTUz03b0n3B6kV5gulwXO6mxooML/9PE7Kl+V3AOjCg==