kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  annotations:
    helm.sh/hook-weight: "355"
  name: {{ .Values.cluster.name }}-aws-creds
  namespace: {{ .Values.cluster.name }}
  creationTimestamp: null
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  template:
    metadata:
      name: {{ .Values.cluster.name }}-aws-creds
      namespace: {{ .Values.cluster.name }}
      creationTimestamp: null
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
    type: Opaque
  encryptedData:
    aws_access_key_id: AgBYbH4NgPvucHfJYvyDiuTto3ugH1yeQ4AilpJv/hWog5TNbipomMjc6xnQ7/y8QlLo1fuwnDA55/zAqqKbfxd8TWNv34yTpLmY5VXnyQtYPhNN48OziVxFlpt9bWu331IHkzaf6ZWGmqZry+8PWDecd1f7xBYM8+VrV9idYpQDBVkQvcg0uy1ZmPFUMXcLQfAFz5HsyoSRto2RlP+BDHwS6E6CqAyruiM9C6AXOgtvINkxk3Z9cbIxFHzi2gs8vC/mlBS3mOrNN75PFbg1zrwAJ9LU0ZfPQ6X/yPEa2jLBg2aJFWxWskWQJ46WX9q0hOMxHTemNXHtcekq2hcGt4I377kuqmMKOlJPwrphvPNhkOwpabHhysvIMA88quTh3DP/uY5nF9og651SYbNbn71cU92wnzv5bSe+RW6HuLsz7tH8P30KpfOY4qECJR3OGCSOLLNd+B9XFrICLjopYWLSHVrdkRljKrWbTkupZv/BzHOiWaUVg6m+ufPr4q5xgnp36JDgA8R1X7SMFg4d+uYVTv5vqbomPq1lnCtNx20B21xYT2RnIfa6Sd1pW9sw+wQOSuoz72wmiEWoV7nvjUJtrlMh2jZbs3a7ZH5AbUkSzDLjpxXhwNd/x7CSExyYh97upZAaJ6VYWg1HuPeQM0Gji14rZpX4Sgm1PSoH+nSZUi09SOOHiTO9psVdibNMPhzPRGITD2KHd8VXDYIDP8IINxYg8w==
    aws_secret_access_key: AgBLYOiyyiKmOtNAADkhCJUjSxLpPhjiXblB870d3o1SAhWuH/LX0m6YWjQBfrFvN1xZmVcaVSRZRyzznG7B0MvS2tFJLW0RlKhD0FnOidkW18U5Sd4WBUDe512bwn/VbVXaM6ghhV/xPt+2/xCvXlLHsM7R+AgK90WPH7Txip6q3xbDr6l9Y6XewpfTZepqHJq1VJWGvjbrRqsmDEyb5CgRs3JTk7DXmrD2lYVLwNsWx6gQct21NBk3k2YdbMjyd1JIZX260Eo/z1lgmI9qXPXoBLGzQeXtp7yRkNf4AlQZBXwd0pcGFIRpinsBgQxTRCh2cckImd89VSpmDZ3TEq7a5PgJ5Akjdkq9xVAQ8U4tR5gKlTQkXGGUJa6YySgi+aPAr+xovBJd7rfr//VM8GamRCI3tiTajcvOXpK38gwy+cKWq7N103r8tfLanw2Utjn3wrAYva3AsAqOMZu316e4RCPzg/IVN4b6sihqtTIoweO25/q+xCPTIGprUJv7++QfPHb85ajNeJes8Bp60ZvxVLYqW5wbbUEIVBU0pTc4kwPbgazeOfCkahO1GEY4a0s/CnXMfB7NlbsTHrObNVdWF/ES3UA53j5ix/BML+ougkRcP8Rt9GJpx9mMOZ9NJKXqTFyGuoJnXkNu3Le4iQJv8/tbuBnxECHIK2UUbqzoh1yv+Z/qoyMfMQf1wzCkAoC1I6+akflgOCTGi2kRd46uBU4QKuHZ0Bhz/d9nbBhxLphz0rbaoH1w
---

# apiVersion: v1
# kind: Secret
# type: Opaque
# metadata:
#   name: xxx-aws-creds
#   namespace: xxx
# stringData:
#   aws_access_key_id: xxx
#   aws_secret_access_key: xxx


