apiVersion: v1
kind: Secret
metadata:
  annotations:
    helm.sh/hook-weight: "355"
  name: {{ .Values.cluster.name }}-install-config
  namespace: {{.Values.cluster.name }}
stringData:
  install-config.yaml: |-
    apiVersion: v1
    metadata:
      name: '{{ .Values.cluster.name }}' 
    baseDomain: {{ .Values.cluster.baseDomain }}
    controlPlane:
      name: master
      architecture: amd64
      hyperthreading: Enabled
      replicas: 1
      platform:
        aws:
          rootVolume:
            iops: 4000
            size: 100
            type: io1
          type: m5.xlarge
    compute:
      - name: worker
        hyperthreading: Enabled
        architecture: amd64
        replicas: 0
        platform:
          aws:
            rootVolume:
              iops: 2000
              size: 100
              type: io1
            type: m5.xlarge
    networking:
      networkType: OpenShiftSDN
      clusterNetwork:
        - cidr: 10.128.0.0/14
          hostPrefix: 23
      machineNetwork:
        - cidr: 10.0.0.0/16
      serviceNetwork:
        - 172.30.0.0/16
    platform:
      aws:
        region: us-west-1
    pullSecret: ''
    sshKey: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOJ36YRzlebn0EMnyA/V06nQFLYtIJ4mSf2fvh24Jq3p lab-user@bastion.w55n5.internal