{{- if .Values.openshift-web-terminal.include }}

---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-web-terminal
  namespace: openshift-operators
spec:
  channel: fast
  installPlanApproval: Manual
  name: web-terminal
  source: redhat-operators
  sourceNamespace: openshift-marketplace

{{ end }}