apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
  name: cluster
spec:
  identityProviders:
  - htpasswd:
      fileData:
        name: htpasswd-secret
    mappingMethod: claim
    name: htpasswd_provider
    type: HTPasswd
  - htpasswd:
      fileData:
        name: htpasswd-secret-acm
    mappingMethod: claim
    name: htpasswd_provider_acm
    type: HTPasswd